# Generated by Django 3.1.7 on 2021-02-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('time', models.TimeField()),
                ('type', models.CharField(max_length=150, verbose_name='Тип оповещения')),
                ('email', models.EmailField(max_length=254)),
                ('group', models.CharField(max_length=150, verbose_name='Группа серверов')),
                ('group_type', models.CharField(max_length=150, verbose_name='Тип группы серверов')),
                ('gps', models.GenericIPAddressField()),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
            ],
        ),
    ]
