# Generated by Django 3.1.7 on 2021-03-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_pdfmaker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PdfMaker',
        ),
    ]
