# Generated by Django 3.1.7 on 2021-03-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_delete_pdfmaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('time', models.TimeField()),
                ('type', models.CharField(max_length=150, verbose_name='Тип оповещения')),
                ('email', models.EmailField(max_length=254)),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
        ),
    ]
